### ISSUE TITLE
sharing of your P1 project

### ISSUE THREAD

**Issue by aeonSolutions** [neographikal/P1-Meter-ESP8266-MQTT#6]
Hi @sandervandegeijn ,
great work!
I'm sharing your P1 meter project on my own home automation project repository:
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home-Automation/README.md](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home-Automation/README.md)

**Comment by aeonSolutions** [comment]
<img height="250px" alt="pcb_layout" src="https://github.com/sandervandegeijn/P1-Meter-ESP8266-MQTT/assets/7936768/f2ca7070-991b-4207-8653-fbc0597531ca">

**Comment by sandervandegeijn** [comment]
Great thanks! It's not the best option out there, I'm currently using esphome with an inverter :)
